const KEY='comicmarket-map-v7';
const EVENTS=['C108',...Array.from({length:22},(_,i)=>`C${109+i}`)];
const DAYS=['1日目','2日目','3日目'];
const PEOPLE=['花岡','菊池','石井','Akio','コナカ','松倉','砂','澤井','風也'];
const COLORS={花岡:'#ef4444',菊池:'#f97316',石井:'#eab308',Akio:'#22c55e',コナカ:'#06b6d4',松倉:'#3b82f6',砂:'#8b5cf6',澤井:'#ec4899',風也:'#64748b'};
const MAPS=[['東123','./maps/east123.webp','https://www.comiket.co.jp/info-a/C108/C108Map_e123_B4.pdf'],['東456','./maps/east456.jpg','https://www.comiket.co.jp/info-a/C107/C107Map_e456_B4.pdf'],['東7','./maps/east7.jpg',''],['西12','./maps/west12.webp','https://www.comiket.co.jp/info-a/C108/C108Map_w12_B4.pdf'],['南12','./maps/south12.jpg','']];
const STATUS=[['NO_LINE','列形成なし'],['WAITING_LINE','列待機中'],['COMPLETED','購入済み'],['SOLD_OUT','完売']];
let state={day:'1日目',map:'東123',filter:'ALL',travelerFilter:'ALL',circles:[]},pending=null,editing=null,scale=1,tx=0,ty=0,pointers=new Map(),gesture=null,moved=false;
const $=id=>document.getElementById(id),yen=n=>'¥'+Math.round(Number(n)||0).toLocaleString('ja-JP');const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const total=c=>(c.items||[]).reduce((n,i)=>n+(+i.qty||0)*(+i.price||0),0);const event=()=>window.CMEvent?.get?.()||'C108';
function normalize(){state.day=DAYS.includes(state.day)?state.day:'1日目';state.map=MAPS.some(m=>m[0]===state.map)?state.map:'東123';state.circles=(Array.isArray(state.circles)?state.circles:[]).map(c=>{let s=c.status==='UNVISITED'?'NO_LINE':c.status==='PLANNED'?'WAITING_LINE':c.status;return {...c,day:DAYS.includes(c.day)?c.day:'1日目',map:MAPS.some(m=>m[0]===c.map)?c.map:'東123',status:STATUS.some(x=>x[0]===s)?s:'NO_LINE',priority:['P1','P2','P3'].includes(c.priority)?c.priority:'OTHER',traveler:PEOPLE.includes(c.traveler)?c.traveler:'',items:Array.isArray(c.items)?c.items:[]}})}
function load(){try{state=JSON.parse(localStorage.getItem(KEY)||'null')||state}catch{}normalize();render()}function save(){normalize();localStorage.setItem(KEY,JSON.stringify(state));render()}
function filtered(){const q=($('search')?.value||'').toLowerCase().trim();return state.circles.filter(c=>c.day===state.day&&(state.filter==='ALL'||c.status===state.filter)&&(state.travelerFilter==='ALL'||c.traveler===state.travelerFilter)&&(!q||[c.name,c.space,c.buyer,c.traveler,...(c.items||[]).map(i=>i.name)].join(' ').toLowerCase().includes(q)))}
function rank(ch){return /[ぁ-ゖ]/.test(ch)?0:/[ァ-ヺ]/.test(ch)?1:/[A-Z]/.test(ch)?2:/[a-z]/.test(ch)?3:4}function cmp(a,b){const d=s=>s.startsWith('東')?0:s.startsWith('西')?1:s.startsWith('南')?2:3,clean=s=>String(s||'').replace(/\s/g,'');let x=clean(a),y=clean(b);if(d(x)!==d(y))return d(x)-d(y);x=x.slice(1);y=y.slice(1);let i=0;while(i<x.length&&i<y.length){if(/\d/.test(x[i])&&/\d/.test(y[i])){let a=x.slice(i).match(/^\d+/)[0],b=y.slice(i).match(/^\d+/)[0];if(+a!==+b)return +a-+b;i+=Math.max(a.length,b.length);continue}let r=rank(x[i])-rank(y[i]);if(r)return r;if(x[i]!==y[i])return x[i].localeCompare(y[i],'ja');i++}return x.length-y.length}
function render(){ $('days').innerHTML=DAYS.map(d=>`<button type="button" data-day="${d}" class="${state.day===d?'active':''}">${d}</button>`).join('');$('maps').innerHTML=MAPS.map(m=>`<button type="button" data-map="${m[0]}" class="${state.map===m[0]?'active':''}">${m[0]}</button>`).join('');$('filters').innerHTML=STATUS.map(s=>`<button type="button" data-filter="${s[0]}" class="${state.filter===s[0]?'active':''}">${s[1]}</button>`).join('');const m=MAPS.find(x=>x[0]===state.map)||MAPS[0];$('mapTitle').textContent=`${event()}・${state.day}・${state.map}`;$('mapImage').src=m[1];$('mapCanvas').style.aspectRatio=state.map==='東123'?'2.31':state.map==='東456'?'1.8':state.map==='東7'?'1':'1.4';renderMarkers();renderList();renderTotals();renderTime();renderEventUI();applyTransform()}
function renderEventUI(){let b=$('eventTabs');if(!b){b=document.createElement('div');b.id='eventTabs';b.className='event-tabs';$('mapSection').prepend(b)}b.innerHTML=EVENTS.map(e=>`<button data-event="${e}" class="${event()===e?'active':''}">${e}</button>`).join('')+`<button id="eventSettings">⚙設定</button>`;let t=$('travelerFilter');if(!t){t=document.createElement('div');t.id='travelerFilter';t.className='toolbar-row';$('listSection').prepend(t)}t.innerHTML=`<label>行く人で絞り込み<select id="travelerSelect"><option value="ALL">全員</option>${PEOPLE.map(p=>`<option value="${p}" ${state.travelerFilter===p?'selected':''}>${p}</option>`).join('')}</select></label>`;if(!$('priority')){const l=document.createElement('label');l.innerHTML='優先度<select id="priority"><option value="OTHER">その他</option><option value="P1">優先度1</option><option value="P2">優先度2</option><option value="P3">優先度3</option></select>';l.id='priorityField';$('traveler').closest('.grid').append(l)}}
function renderMarkers(){const cs=state.circles.filter(c=>c.day===state.day&&c.map===state.map&&(state.travelerFilter==='ALL'||c.traveler===state.travelerFilter));$('markers').innerHTML=cs.map(c=>{const color=COLORS[c.traveler]||'#64748b',border=c.status==='COMPLETED'?'#16a34a':c.status==='SOLD_OUT'?'#dc2626':'#fff';return `<button class="marker" data-marker="${c.id}" style="left:${c.x*100}%;top:${c.y*100}%;background:${color};border-color:${border}">${c.priority!=='OTHER'?'★':''}</button>`}).join('')}
function renderList(){const rs=[...filtered()].sort((a,b)=>cmp(a.space,b.space)||a.name.localeCompare(b.name,'ja'));$('empty').classList.toggle('hidden',rs.length>0);$('list').innerHTML=rs.map(c=>`<article class="purchase" data-open="${c.id}"><div><h3>${esc(c.name)} <span class="status ${c.status}">${STATUS.find(x=>x[0]===c.status)?.[1]}</span>${c.priority!=='OTHER'?' ★':''}</h3><p>${esc(c.space)} ・ 📍 ${esc(c.traveler||'未指定')} ・ 👤 ${esc(c.buyer||'未入力')}</p><div>${(c.items||[]).map(i=>`<span class="item-chip">${esc(i.name)} ×${i.qty} ${yen(i.qty*i.price)}</span>`).join('')}</div><div class="action-row">${STATUS.map(s=>`<button class="ghost statusBtn" data-id="${c.id}" data-status="${s[0]}" type="button">${s[1]}</button>`).join('')}</div></div><div class="money">${yen(total(c))}</div></article>`).join('')}
function renderTotals(){const cs=state.circles.filter(c=>c.day===state.day);$('circleCount').textContent=cs.length+'件';$('circleCount2').textContent=cs.length;$('itemCount').textContent=cs.reduce((n,c)=>n+(c.items||[]).reduce((x,i)=>x+(+i.qty||0),0),0);$('grandTotal').textContent=yen(cs.reduce((n,c)=>n+total(c),0));$('dayTotals').innerHTML=DAYS.map(d=>`<div class="day-total"><span>${d}</span><strong>${yen(state.circles.filter(c=>c.day===d).reduce((n,c)=>n+total(c),0))}</strong></div>`).join('')}
function renderTime(){const rs=state.circles.filter(c=>(c.status==='COMPLETED'&&c.completedAt)||(c.status==='SOLD_OUT'&&c.soldOutAt)).sort((a,b)=>new Date(b.completedAt||b.soldOutAt)-new Date(a.completedAt||a.soldOutAt));$('timeEmpty').classList.toggle('hidden',rs.length>0);$('timeList').innerHTML=rs.map(c=>`<article class="time-row"><strong>${esc(c.name)}</strong><span>${c.status==='COMPLETED'?'購入済み':'完売'}　${new Date(c.completedAt||c.soldOutAt).toLocaleString('ja-JP')}</span></article>`).join('')}
function addItem(i={}){const r=document.createElement('div');r.className='item-row';r.innerHTML=`<label>商品<input class="i-name" value="${esc(i.name||'')}"></label><label>数量<input class="i-qty" type="number" min="1" value="${i.qty||1}"></label><label>単価<input class="i-price" type="number" min="0" value="${i.price||0}"></label><button type="button" class="ghost removeItem">×</button>`;r.querySelectorAll('input').forEach(x=>x.oninput=formTotal);r.querySelector('.removeItem').onclick=()=>{r.remove();formTotal()};$('itemRows').append(r)}function formItems(){return [...document.querySelectorAll('#itemRows .item-row')].map(r=>({name:r.querySelector('.i-name').value.trim(),qty:+r.querySelector('.i-qty').value||1,price:+r.querySelector('.i-price').value||0})).filter(x=>x.name)}function formTotal(){$('formTotal').textContent=yen(formItems().reduce((n,i)=>n+i.qty*i.price,0))}
function openForm(x,y,id=null){pending={x,y};editing=id;const c=id&&state.circles.find(x=>x.id===id);$('circleName').value=c?.name||'';$('space').value=c?.space||'';$('traveler').value=c?.traveler||'';$('buyer').value=c?.buyer||'';$('priority').value=c?.priority||'OTHER';$('itemRows').innerHTML='';(c?.items?.length?c.items:[{}]).forEach(addItem);$('positionText').textContent=`地図位置 ${(x*100).toFixed(1)}% / ${(y*100).toFixed(1)}%`;$('formCard').classList.remove('hidden');formTotal()}function closeForm(){$('formCard').classList.add('hidden');pending=editing=null}
function bounds(){const v=$('mapViewport'),c=$('mapCanvas');return{x:Math.max(0,(c.offsetWidth*scale-v.clientWidth)/2),y:Math.max(0,(c.offsetHeight*scale-v.clientHeight)/2)}}function applyTransform(){const b=bounds();tx=Math.max(-b.x,Math.min(b.x,tx));ty=Math.max(-b.y,Math.min(b.y,ty));$('mapCanvas').style.transform=`translate3d(${tx}px,${ty}px,0) scale(${scale})`;if($('zoomReset'))$('zoomReset').textContent=Math.round(scale*100)+'%'}function resetZoom(){scale=1;tx=ty=0;applyTransform()}function zoom(n){scale=Math.max(.8,Math.min(5,n));applyTransform()}function point(x,y){const r=$('mapCanvas').getBoundingClientRect();return{x:Math.max(0,Math.min(1,(x-r.left)/r.width)),y:Math.max(0,Math.min(1,(y-r.top)/r.height))}}
$('days').onclick=e=>{const b=e.target.closest('[data-day]');if(b){state.day=b.dataset.day;resetZoom();render()}};$('maps').onclick=e=>{const b=e.target.closest('[data-map]');if(b){state.map=b.dataset.map;resetZoom();render()}};$('filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){state.filter=b.dataset.filter;render()}};$('registerMode').onclick=()=>{const on=!$('mapViewport').classList.contains('registering');$('mapViewport').classList.toggle('registering',on);$('mapModeHint').classList.toggle('hidden',!on);$('registerMode').textContent=on?'登録モード終了':'＋ 地図から登録'};$('zoomIn').onclick=()=>zoom(scale+.25);$('zoomOut').onclick=()=>zoom(scale-.25);$('zoomReset').onclick=resetZoom;$('cancelForm').onclick=closeForm;$('addItem').onclick=()=>addItem();$('search').oninput=render;
$('saveCircle').onclick=()=>{if(!pending)return;const name=$('circleName').value.trim(),space=$('space').value.trim(),items=formItems();if(!name||!space||!items.length)return alert('サークル名・スペース・購入品は必須です');const d={day:state.day,map:state.map,name,space,traveler:$('traveler').value,buyer:$('buyer').value.trim(),priority:$('priority').value,items,x:pending.x,y:pending.y};if(editing)Object.assign(state.circles.find(c=>c.id===editing),d);else state.circles.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),...d,status:'NO_LINE'});save();closeForm()};
$('list').onclick=e=>{const s=e.target.closest('.statusBtn');if(s){e.stopPropagation();const c=state.circles.find(c=>c.id===s.dataset.id);if(c){c.status=s.dataset.status;const now=new Date().toISOString();if(c.status==='COMPLETED'){c.completedAt=now;delete c.soldOutAt}else if(c.status==='SOLD_OUT'){c.soldOutAt=now;delete c.completedAt}else{delete c.completedAt;delete c.soldOutAt}save()}return}const a=e.target.closest('[data-open]');if(a){const c=state.circles.find(c=>c.id===a.dataset.open);if(c)openForm(c.x,c.y,c.id)}};$('markers').onclick=e=>{const b=e.target.closest('[data-marker]');if(b){const c=state.circles.find(c=>c.id===b.dataset.marker);if(c)openForm(c.x,c.y,c.id)}};$('officialLink').onclick=()=>window.open((MAPS.find(m=>m[0]===state.map)||MAPS[0])[2]||'https://www.comiket.co.jp/','_blank','noopener');
const vp=$('mapViewport');vp.addEventListener('pointerdown',e=>{if(e.target.closest('.marker'))return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});moved=false;if(pointers.size===1)gesture={x:e.clientX,y:e.clientY,tx,ty,dist:null};else{const a=[...pointers.values()];gesture={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),scale}}},{passive:false});vp.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&gesture?.dist===null){const p=pointers.get(e.pointerId);tx=gesture.tx+p.x-gesture.x;ty=gesture.ty+p.y-gesture.y;if(Math.hypot(p.x-gesture.x,p.y-gesture.y)>6)moved=true;applyTransform()}else if(pointers.size===2){const a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);scale=Math.max(.8,Math.min(5,gesture.scale*d/gesture.dist));moved=true;applyTransform()}},{passive:false});vp.addEventListener('pointerup',e=>{const g=gesture;pointers.delete(e.pointerId);if(g&&!moved&&!pointers.size&&g.dist===null&&vp.classList.contains('registering')){const p=point(e.clientX,e.clientY);openForm(p.x,p.y);vp.classList.remove('registering');$('mapModeHint').classList.add('hidden');$('registerMode').textContent='＋ 地図から登録'}if(!pointers.size)gesture=null},{passive:false});vp.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);if(!pointers.size)gesture=null});vp.addEventListener('wheel',e=>{e.preventDefault();zoom(scale+(e.deltaY<0?.15:-.15))},{passive:false});
document.addEventListener('change',e=>{if(e.target.id==='travelerSelect'){state.travelerFilter=e.target.value;render()}},true);document.addEventListener('click',e=>{const ev=e.target.closest('[data-event]');if(ev){CMEvent.switch(ev.dataset.event);return}if(e.target.id==='eventSettings'){alert('会期ごとのサークル・日付・地図データは会期ごとに独立保存されます。C109以降の公式地図が公開されたら会期別に登録できます。');return}const nav=e.target.closest('.bottom-nav button');if(nav){e.preventDefault();const id={map:'mapSection',list:'listSection',money:'moneySection',time:'timeSection'}[nav.dataset.nav];document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x===nav));document.querySelectorAll('main>section').forEach(s=>{if(['mapSection','listSection','moneySection','timeSection'].includes(s.id))s.classList.toggle('hidden',s.id!==id)});$(id)?.scrollIntoView({behavior:'smooth',block:'start'})}},true);window.addEventListener('resize',applyTransform);load();
