(()=>{'use strict';
const KEY='comicmarket-map-v7',DAYS=['1日目','2日目','3日目'],EVENTS=['C108','C109','C110','C111','C112','C113','C114','C115'],PEOPLE=['花岡','菊池','石井','Akio','コナカ','松倉','砂','澤井','風也'];
const COLORS={花岡:'#ef4444',菊池:'#f97316',石井:'#eab308',Akio:'#22c55e',コナカ:'#06b6d4',松倉:'#3b82f6',砂:'#8b5cf6',澤井:'#ec4899',風也:'#64748f'};
const MAPS=[['東123','./maps/east123.webp','https://www.comiket.co.jp/info-a/C108/C108Map_e123_B4.pdf'],['東456','./maps/east456.jpg','https://www.comiket.co.jp/info-a/C107/C107Map_e456_B4.pdf'],['東7','./maps/east7.jpg',''],['西12','./maps/west12.webp','https://www.comiket.co.jp/info-a/C108/C108Map_w12_B4.pdf'],['南12','./maps/south12.jpg','']];
const STATUS=[['NO_LINE','列形成なし'],['WAITING_LINE','列待機中'],['COMPLETED','購入済み'],['SOLD_OUT','完売']];
const $=id=>document.getElementById(id),yen=n=>'¥'+Math.round(Number(n)||0).toLocaleString('ja-JP'),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let state={day:'1日目',map:'東123',filter:'ALL',travelerFilter:'ALL',sort:false,circles:[]},pending=null,editing=null,scale=1,tx=0,ty=0,pointers=new Map(),gesture=null;
const event=()=>window.CMEvent?.get?.()||'C108',total=c=>(c.items||[]).reduce((n,i)=>n+(+i.qty||0)*(+i.price||0),0);
function normalize(){state.day=DAYS.includes(state.day)?state.day:'1日目';state.map=MAPS.some(x=>x[0]===state.map)?state.map:'東123';state.filter=STATUS.some(x=>x[0]===state.filter)||state.filter==='ALL'?state.filter:'ALL';state.travelerFilter=PEOPLE.includes(state.travelerFilter)?state.travelerFilter:'ALL';state.circles=(Array.isArray(state.circles)?state.circles:[]).map(c=>({...c,day:DAYS.includes(c.day)?c.day:'1日目',map:MAPS.some(x=>x[0]===c.map)?c.map:'東123',status:c.status==='UNVISITED'?'NO_LINE':c.status==='PLANNED'?'WAITING_LINE':STATUS.some(x=>x[0]===c.status)?c.status:'NO_LINE',priority:['P1','P2','P3'].includes(c.priority)?c.priority:'OTHER',traveler:PEOPLE.includes(c.traveler)?c.traveler:'',items:Array.isArray(c.items)?c.items:[]}))}
function load(){try{state=JSON.parse(localStorage.getItem(KEY)||'null')||state}catch{}normalize();render();navTo('map')}
function save(){normalize();localStorage.setItem(KEY,JSON.stringify(state))}
function rank(s){const c=(String(s||'').match(/[ぁ-ゖァ-ヺA-Za-z]/)||[])[0];return !c?4:/[ぁ-ゖ]/.test(c)?0:/[ァ-ヺ]/.test(c)?1:/[A-Z]/.test(c)?2:3}
function sortKey(s){return String(s||'').replace(/\s/g,'')}
function cmp(a,b){let x=sortKey(a),y=sortKey(b),rx=rank(x),ry=rank(y);if(rx!==ry)return rx-ry;const dir=s=>s.startsWith('東')?0:s.startsWith('西')?1:s.startsWith('南')?2:3,dx=dir(x),dy=dir(y);if(dx!==dy)return dx-dy;const nx=+(x.match(/\d+/)||['999999'])[0],ny=+(y.match(/\d+/)||['999999'])[0];if(nx!==ny)return nx-ny;return x.localeCompare(y,'ja')}
function render(){
 $('days').innerHTML=DAYS.map(d=>`<button type="button" data-day="${d}" class="${state.day===d?'active':''}">${d}</button>`).join('');
 $('maps').innerHTML=MAPS.map(m=>`<button type="button" data-map="${m[0]}" class="${state.map===m[0]?'active':''}">${m[0]}</button>`).join('');
 $('filters').innerHTML='<button type="button" data-filter="ALL" class="'+(state.filter==='ALL'?'active':'')+'">すべて</button>'+STATUS.map(s=>`<button type="button" data-filter="${s[0]}" class="${state.filter===s[0]?'active':''}">${s[1]}</button>`).join('');
 $('mapTitle').textContent=`${event()}・${state.day}・${state.map}`;$('mapImage').src=(MAPS.find(x=>x[0]===state.map)||MAPS[0])[1];$('mapCanvas').style.aspectRatio=state.map==='東123'?'2.31':state.map==='東456'?'1.8':state.map==='東7'?'1':'1.4';
 renderEvents();renderTraveler();renderMarkers();renderList();renderTotals();renderTime();applyTransform();window.CMHighResMap?.refresh?.();
}
function renderEvents(){let el=$('eventTabs');if(!el){el=document.createElement('div');el.id='eventTabs';el.className='event-tabs';$('mapSection').prepend(el)}el.innerHTML=EVENTS.map(e=>`<button type="button" data-event="${e}" class="${event()===e?'active':''}">${e}</button>`).join('')}
function renderTraveler(){const el=$('travelerFilter');if(el)el.innerHTML=`<label>行く人で絞り込み <select id="travelerSelect"><option value="ALL">全員</option>${PEOPLE.map(p=>`<option value="${p}" ${state.travelerFilter===p?'selected':''}>${p}</option>`).join('')}</select></label>`}
function visible(){const q=($('search')?.value||'').toLowerCase().trim();return state.circles.filter(c=>c.day===state.day&&(state.filter==='ALL'||c.status===state.filter)&&(state.travelerFilter==='ALL'||c.traveler===state.travelerFilter)&&(!q||[c.name,c.space,c.buyer,c.traveler,...(c.items||[]).map(i=>i.name)].join(' ').toLowerCase().includes(q)))}
function renderMarkers(){const cs=state.circles.filter(c=>c.day===state.day&&c.map===state.map&&(state.travelerFilter==='ALL'||c.traveler===state.travelerFilter));$('markers').innerHTML=cs.map(c=>{const border=c.status==='COMPLETED'?'#16a34a':c.status==='SOLD_OUT'?'#dc2626':'#fff';return `<button type="button" class="marker" data-marker="${c.id}" title="${esc(c.name)}" style="left:${c.x*100}%;top:${c.y*100}%;background:${COLORS[c.traveler]||'#64748b'};border-color:${border}">${c.priority!=='OTHER'?'★':''}</button>`}).join('')}
function renderList(){const rs=visible();if(state.sort)rs.sort((a,b)=>cmp(a.space,b.space)||a.name.localeCompare(b.name,'ja'));$('empty').classList.toggle('hidden',rs.length>0);$('list').innerHTML=rs.map(c=>`<article class="purchase" data-open="${c.id}"><div><h3>${esc(c.name)} <span class="status ${c.status}">${STATUS.find(x=>x[0]===c.status)?.[1]}</span>${c.priority!=='OTHER'?' ★':''}</h3><p>${esc(c.space)} ・ 📍 ${esc(c.traveler||'未指定')} ・ 👤 ${esc(c.buyer||'未入力')}</p><div>${(c.items||[]).map(i=>`<span class="item-chip">${esc(i.name)} ×${i.qty} ${yen(i.qty*i.price)}</span>`).join('')}</div><div class="action-row">${STATUS.map(s=>`<button type="button" class="ghost statusBtn" data-id="${c.id}" data-status="${s[0]}">${s[1]}</button>`).join('')}</div></div><div class="money">${yen(total(c))}</div></article>`).join('')}
function renderTotals(){const cs=state.circles.filter(c=>c.day===state.day);$('circleCount').textContent=cs.length+'件';$('circleCount2').textContent=cs.length;$('itemCount').textContent=cs.reduce((n,c)=>n+(c.items||[]).reduce((x,i)=>x+(+i.qty||0),0),0);$('grandTotal').textContent=yen(cs.reduce((n,c)=>n+total(c),0));$('dayTotals').innerHTML=DAYS.map(d=>`<div class="day-total"><span>${d}</span><strong>${yen(state.circles.filter(c=>c.day===d).reduce((n,c)=>n+total(c),0))}</strong></div>`).join('');$('travelerTotals').innerHTML=PEOPLE.map(p=>`<div class="day-total"><span>${p}</span><strong>${yen(state.circles.filter(c=>c.day===state.day&&c.traveler===p).reduce((n,c)=>n+total(c),0))}</strong></div>`).join('')}
function renderTime(){const rs=state.circles.filter(c=>(c.status==='COMPLETED'&&c.completedAt)||(c.status==='SOLD_OUT'&&c.soldOutAt)).sort((a,b)=>new Date(b.completedAt||b.soldOutAt)-new Date(a.completedAt||a.soldOutAt));$('timeEmpty').classList.toggle('hidden',rs.length>0);$('timeList').innerHTML=rs.map(c=>`<article class="time-row"><strong>${esc(c.name)}</strong><span>${new Date(c.completedAt||c.soldOutAt).toLocaleString('ja-JP')}</span></article>`).join('')}
function formItems(){return [...document.querySelectorAll('#itemRows .item-row')].map(r=>({name:r.querySelector('.i-name').value.trim(),qty:+r.querySelector('.i-qty').value||1,price:+r.querySelector('.i-price').value||0})).filter(x=>x.name)}
function formTotal(){$('formTotal').textContent=yen(formItems().reduce((n,i)=>n+i.qty*i.price,0))}window.formTotal=formTotal;
function addItem(i={}){const r=document.createElement('div');r.className='item-row';r.innerHTML=`<label>商品<input class="i-name" autocomplete="off" value="${esc(i.name||'')}"></label><label>数量<input class="i-qty" type="number" min="1" value="${i.qty||1}"></label><label>単価<input class="i-price" type="number" min="0" value="${i.price||0}"></label><button type="button" class="ghost removeItem">×</button>`;r.querySelectorAll('input').forEach(x=>x.addEventListener('input',formTotal));r.querySelector('.removeItem').onclick=()=>{r.remove();formTotal()};$('itemRows').appendChild(r);formTotal()}
function openForm(x,y,id){pending={x,y};editing=id||null;const c=id&&state.circles.find(v=>v.id===id);$('circleName').value=c?.name||'';$('space').value=c?.space||'';$('traveler').value=c?.traveler||'';$('buyer').value=c?.buyer||'';$('priority').value=c?.priority||'OTHER';$('itemRows').innerHTML='';(c?.items?.length?c.items:[{}]).forEach(addItem);$('positionText').textContent=`地図位置 ${(x*100).toFixed(1)}% / ${(y*100).toFixed(1)}%`;$('formCard').classList.remove('hidden');formTotal()}
function closeForm(){$('formCard').classList.add('hidden');pending=editing=null}
function bounds(){const v=$('mapViewport'),c=$('mapCanvas');return{x:Math.max(0,(c.offsetWidth*scale-v.clientWidth)/2),y:Math.max(0,(c.offsetHeight*scale-v.clientHeight)/2)}}function applyTransform(){const b=bounds();tx=Math.max(-b.x,Math.min(b.x,tx));ty=Math.max(-b.y,Math.min(b.y,ty));$('mapCanvas').style.transform=`translate3d(${tx}px,${ty}px,0) scale(${scale})`;if($('zoomReset'))$('zoomReset').textContent=Math.round(scale*100)+'%'}function resetZoom(){scale=1;tx=ty=0;applyTransform()}function zoom(n){scale=Math.max(.8,Math.min(5,n));applyTransform()}function point(x,y){const r=$('mapCanvas').getBoundingClientRect();return{x:Math.max(0,Math.min(1,(x-r.left)/r.width)),y:Math.max(0,Math.min(1,(y-r.top)/r.height))}}
function navTo(name){const ids={map:'mapSection',list:'listSection',money:'moneySection',time:'timeSection'};Object.entries(ids).forEach(([k,id])=>$(id)?.classList.toggle('hidden',k!==name));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));$(ids[name])?.scrollIntoView({behavior:'smooth',block:'start'})}
$('days').onclick=e=>{const b=e.target.closest('[data-day]');if(b){state.day=b.dataset.day;resetZoom();render()}};$('maps').onclick=e=>{const b=e.target.closest('[data-map]');if(b){state.map=b.dataset.map;resetZoom();render()}};$('filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){state.filter=b.dataset.filter;renderList()}};$('registerMode').onclick=()=>{const on=!$('mapViewport').classList.contains('registering');$('mapViewport').classList.toggle('registering',on);$('mapModeHint').classList.toggle('hidden',!on);$('registerMode').textContent=on?'登録モード終了':'＋ 地図から登録'};$('zoomIn').onclick=()=>zoom(scale+.25);$('zoomOut').onclick=()=>zoom(scale-.25);$('zoomReset').onclick=resetZoom;$('cancelForm').onclick=closeForm;$('addItem').onclick=()=>addItem();$('search').oninput=renderList;$('sortList').onclick=()=>{state.sort=!state.sort;$('sortList').textContent=state.sort?'並び替え：ON':'並び替え：東→西→南';renderList()};
$('saveCircle').onclick=()=>{if(!pending)return;const name=$('circleName').value.trim(),space=$('space').value.trim(),items=formItems();if(!name||!space||!items.length)return alert('サークル名・スペース・購入品は必須です');const d={day:state.day,map:state.map,name,space,traveler:$('traveler').value,buyer:$('buyer').value.trim(),priority:$('priority').value,items,x:pending.x,y:pending.y};if(editing)Object.assign(state.circles.find(c=>c.id===editing),d);else state.circles.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),...d,status:'NO_LINE'});save();closeForm()};
$('list').onclick=e=>{const s=e.target.closest('.statusBtn');if(s){e.stopPropagation();const c=state.circles.find(v=>v.id===s.dataset.id);if(!c)return;c.status=s.dataset.status;const now=new Date().toISOString();if(c.status==='COMPLETED'){c.completedAt=now;delete c.soldOutAt}else if(c.status==='SOLD_OUT'){c.soldOutAt=now;delete c.completedAt}else{delete c.completedAt;delete c.soldOutAt}save();return}const a=e.target.closest('[data-open]');if(a){const c=state.circles.find(v=>v.id===a.dataset.open);if(c)openForm(c.x,c.y,c.id)}};$('markers').onclick=e=>{const b=e.target.closest('[data-marker]');if(b){const c=state.circles.find(v=>v.id===b.dataset.marker);if(c)openForm(c.x,c.y,c.id)}};$('officialLink').onclick=()=>window.open((MAPS.find(m=>m[0]===state.map)||MAPS[0])[2]||'https://www.comiket.co.jp/','_blank','noopener');document.querySelectorAll('.bottom-nav [data-nav]').forEach(b=>b.onclick=()=>navTo(b.dataset.nav));
document.addEventListener('change',e=>{if(e.target.id==='travelerSelect'){state.travelerFilter=e.target.value;save();renderMarkers()}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-event]');if(b){e.preventDefault();window.CMEvent?.switch?.(b.dataset.event)}});
const vp=$('mapViewport');vp.addEventListener('pointerdown',e=>{if(e.target.closest('.marker'))return;if(vp.classList.contains('registering'))return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)gesture={x:e.clientX,y:e.clientY,tx,ty,dist:null};else{const a=[...pointers.values()];gesture={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),scale}}},{passive:false});vp.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&gesture?.dist===null){const p=pointers.get(e.pointerId);tx=gesture.tx+p.x-gesture.x;ty=gesture.ty+p.y-gesture.y;applyTransform()}else if(pointers.size>1&&gesture?.dist){const a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);zoom(gesture.scale*d/gesture.dist)}},{passive:false});vp.addEventListener('pointerup',e=>{if(vp.classList.contains('registering')){const p=point(e.clientX,e.clientY);openForm(p.x,p.y);vp.classList.remove('registering');$('mapModeHint').classList.add('hidden');$('registerMode').textContent='＋ 地図から登録'}pointers.delete(e.pointerId);if(!pointers.size)gesture=null},{passive:false});vp.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);if(!pointers.size)gesture=null},{passive:true});window.addEventListener('resize',applyTransform,{passive:true});load();
})();
