import React,{useEffect,useMemo,useState}from"react";
import{Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View,Platform}from"react-native";
import{StatusBar}from"expo-status-bar";
import{initialCircles}from"./src/data/circles";
import{CircleData,CircleStatus,PurchaseItem,allPurchaseTotal,circleTotal}from"./src/types";
import{InteractiveSvgMap}from"./src/components/InteractiveSvgMap";
import{CircleList}from"./src/components/CircleList";
const KEY="comiket-map-circles-v3"; const MAP_KEY="comiket-map-official-map-v1";
const OFFICIAL_MAP="https://www.comiket.co.jp/info-a/C108/C108CtlgMap.html";
const blankForm={name:"",space:"",purchaser:"",item:"",qty:"1",price:"0",x:"500",y:"300"};
export default function App(){
 const[circles,setCircles]=useState<CircleData[]>(initialCircles); const[selectedId,setSelectedId]=useState<string|null>(null); const[query,setQuery]=useState(""); const[filter,setFilter]=useState<"ALL"|CircleStatus>("ALL"); const[day,setDay]=useState("1日目"); const[editing,setEditing]=useState(false); const[mapUrl,setMapUrl]=useState(""); const[form,setForm]=useState(blankForm); const[itemForm,setItemForm]=useState({item:"",qty:"1",price:"0"});
 useEffect(()=>{if(Platform.OS==="web"){try{const v=localStorage.getItem(KEY);if(v)setCircles(JSON.parse(v));const m=localStorage.getItem(MAP_KEY);if(m)setMapUrl(m)}catch{}}},[]);
 useEffect(()=>{if(Platform.OS==="web"){localStorage.setItem(KEY,JSON.stringify(circles));localStorage.setItem(MAP_KEY,mapUrl)}},[circles,mapUrl]);
 const visible=useMemo(()=>circles.filter(c=>(c.day===day)&&(!query||c.name.toLowerCase().includes(query.toLowerCase())||c.space.toLowerCase().includes(query.toLowerCase())||c.purchaser.toLowerCase().includes(query.toLowerCase()))&&(filter==="ALL"||c.status===filter)),[circles,query,filter,day]);
 const selected=circles.find(c=>c.id===selectedId); const total=allPurchaseTotal(circles); const dayTotal=allPurchaseTotal(circles.filter(c=>c.day===day));
 const onMapTap=(x:number,y:number)=>{setForm(f=>({...f,x:Math.round(x).toString(),y:Math.round(y).toString()}));setEditing(true)};
 const add=()=>{if(!form.name.trim()||!form.space.trim())return;const purchase:PurchaseItem[] = form.item.trim()?[{id:Date.now().toString(),item:form.item.trim(),quantity:Math.max(1,Number(form.qty)||1),unitPrice:Math.max(0,Number(form.price)||0)}]:[];const id=`${day}-${Date.now()}`;const c:CircleData={id,day,space:form.space.trim(),name:form.name.trim(),purchaser:form.purchaser.trim(),status:"UNVISITED",x:Number(form.x)||500,y:Number(form.y)||300,purchases:purchase};setCircles(p=>[...p,c]);setSelectedId(id);setForm(blankForm);setEditing(false)};
 const update=(status:CircleStatus)=>selected&&setCircles(p=>p.map(c=>c.id===selected.id?{...c,status}:c));
 const addItem=()=>{if(!selected||!itemForm.item.trim())return;const item:PurchaseItem={id:Date.now().toString(),item:itemForm.item.trim(),quantity:Math.max(1,Number(itemForm.qty)||1),unitPrice:Math.max(0,Number(itemForm.price)||0)};setCircles(p=>p.map(c=>c.id===selected.id?{...c,purchases:[...c.purchases,item]}:c));setItemForm({item:"",qty:"1",price:"0"})};
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><ScrollView contentContainerStyle={s.page}>
 <Text style={s.title}>コミケマップ</Text><Text style={s.sub}>公式白地図＋タップ登録＋購入管理</Text>
 <View style={s.card}><Text style={s.section}>開催日</Text><View style={s.filters}>{["1日目","2日目","3日目"].map(d=><Pressable key={d} onPress={()=>setDay(d)} style={[s.filter,day===d&&s.active]}><Text style={day===d?s.fta:s.ft}>{d}</Text></Pressable>)}</View><Text style={s.help}>公式のC108サークルスペース地図はコミケット準備会公開ページを基準にします。</Text><Pressable onPress={()=>Platform.OS==="web"&&window.open(OFFICIAL_MAP,"_blank")} style={s.official}><Text style={s.officialText}>公式白地図・配置図を開く</Text></Pressable><TextInput value={mapUrl} onChangeText={setMapUrl} placeholder="公式白地図の画像URLを貼り付け" style={s.input} autoCapitalize="none"/><Text style={s.help}>画像URLを設定すると、アプリ内の背景として表示されます。</Text></View>
 <View style={s.map}><InteractiveSvgMap circles={visible} selectedId={selectedId} mapUrl={mapUrl} onSelectCircle={setSelectedId} onMapTap={onMapTap}/></View>
 <View style={s.card}><Text style={s.tapHelp}>📍 マップ上をタップ → その位置を自動入力してサークル登録</Text><TextInput value={query} onChangeText={setQuery} placeholder="サークル名・スペース・購入者を検索" style={s.input}/><View style={s.filters}>{[["ALL","すべて"],["UNVISITED","未訪問"],["COMPLETED","訪問済み"],["SOLD_OUT","完売"]].map(([k,l])=><Pressable key={k} onPress={()=>setFilter(k as any)} style={[s.filter,filter===k&&s.active]}><Text style={filter===k?s.fta:s.ft}>{l}</Text></Pressable>)}</View></View>
 <View style={s.totalCard}><Text style={s.totalLabel}>全体購入予定総額</Text><Text style={s.total}>¥{total.toLocaleString()}</Text><Text style={s.dayTotal}>{day}：¥{dayTotal.toLocaleString()}</Text></View>
 <View style={s.card}><View style={s.header}><Text style={s.section}>サークル登録</Text><Pressable onPress={()=>setEditing(!editing)}><Text style={s.link}>{editing?"閉じる":"＋登録"}</Text></Pressable></View>{editing&&<View style={s.editor}><TextInput value={form.name} onChangeText={v=>setForm({...form,name:v})} placeholder="サークル名" style={s.input}/><TextInput value={form.space} onChangeText={v=>setForm({...form,space:v})} placeholder="スペース（例：東7 A-12a）" style={s.input}/><TextInput value={form.purchaser} onChangeText={v=>setForm({...form,purchaser:v})} placeholder="購入者名" style={s.input}/><Text style={s.label}>購入するもの</Text><TextInput value={form.item} onChangeText={v=>setForm({...form,item:v})} placeholder="商品名" style={s.input}/><View style={s.row}><TextInput value={form.qty} onChangeText={v=>setForm({...form,qty:v})} keyboardType="numeric" placeholder="数量" style={[s.input,s.coord]}/><TextInput value={form.price} onChangeText={v=>setForm({...form,price:v})} keyboardType="numeric" placeholder="単価" style={[s.input,s.coord]}/></View><Text style={s.help}>購入予定額：¥{((Number(form.qty)||0)*(Number(form.price)||0)).toLocaleString()}</Text><View style={s.row}><TextInput value={form.x} onChangeText={v=>setForm({...form,x:v})} keyboardType="numeric" placeholder="X" style={[s.input,s.coord]}/><TextInput value={form.y} onChangeText={v=>setForm({...form,y:v})} keyboardType="numeric" placeholder="Y" style={[s.input,s.coord]}/></View><Pressable onPress={add} style={s.add}><Text style={s.addText}>サークルを登録</Text></Pressable></View>}</View>
 {selected&&<View style={s.detail}><Text style={s.dt}>{selected.name}</Text><Text>{selected.space}　/　購入者：{selected.purchaser||"未設定"}</Text><Text style={s.circleTotal}>このサークル：¥{circleTotal(selected).toLocaleString()}</Text><View style={s.filters}>{[["UNVISITED","未訪問"],["COMPLETED","訪問済み"],["SOLD_OUT","完売"]].map(([k,l])=><Pressable key={k} onPress={()=>update(k as CircleStatus)} style={s.action}><Text style={s.at}>{l}</Text></Pressable>)}</View><Text style={s.label}>購入品追加</Text><TextInput value={itemForm.item} onChangeText={v=>setItemForm({...itemForm,item:v})} placeholder="商品名" style={s.input}/><View style={s.row}><TextInput value={itemForm.qty} onChangeText={v=>setItemForm({...itemForm,qty:v})} keyboardType="numeric" placeholder="数量" style={[s.input,s.coord]}/><TextInput value={itemForm.price} onChangeText={v=>setItemForm({...itemForm,price:v})} keyboardType="numeric" placeholder="単価" style={[s.input,s.coord]}/></View><Pressable onPress={addItem} style={s.add}><Text style={s.addText}>購入品を追加</Text></Pressable>{selected.purchases.map(p=><View key={p.id} style={s.purchaseRow}><Text style={{flex:1}}>{p.item} × {p.quantity}</Text><Text>¥{(p.quantity*p.unitPrice).toLocaleString()}</Text></View>)}</View>}
 <View style={s.card}><Text style={s.section}>サークル一覧（{visible.length}件）</Text><CircleList circles={visible} onSelect={setSelectedId}/></View>
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F1F5F9"},page:{width:"100%",maxWidth:1000,alignSelf:"center",padding:16,gap:14},title:{fontSize:30,fontWeight:"800",color:"#0F172A"},sub:{color:"#64748B"},map:{backgroundColor:"#fff",borderRadius:18,padding:8},card:{backgroundColor:"#fff",borderRadius:16,padding:14},section:{fontSize:20,fontWeight:"800",color:"#0F172A"},input:{borderWidth:1,borderColor:"#CBD5E1",borderRadius:10,padding:12,fontSize:16,backgroundColor:"#F8FAFC"},filters:{flexDirection:"row",gap:8,flexWrap:"wrap",paddingTop:10},filter:{paddingVertical:9,paddingHorizontal:14,borderRadius:20,backgroundColor:"#E2E8F0"},active:{backgroundColor:"#2563EB"},ft:{color:"#334155",fontWeight:"700"},fta:{color:"#fff",fontWeight:"700"},help:{color:"#64748B",fontSize:12,marginTop:8},official:{marginTop:10,backgroundColor:"#0F172A",padding:12,borderRadius:10,alignItems:"center"},officialText:{color:"#fff",fontWeight:"800"},tapHelp:{color:"#1D4ED8",fontWeight:"700",marginBottom:10},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},link:{color:"#2563EB",fontWeight:"800"},editor:{gap:10,marginTop:12},label:{fontWeight:"800",color:"#334155",marginTop:4},row:{flexDirection:"row",gap:10},coord:{flex:1},add:{backgroundColor:"#2563EB",padding:13,borderRadius:10,alignItems:"center"},addText:{color:"#fff",fontWeight:"800"},detail:{backgroundColor:"#EFF6FF",borderRadius:16,padding:16},dt:{fontSize:20,fontWeight:"800",color:"#1E3A8A"},circleTotal:{fontSize:18,fontWeight:"800",marginTop:8},action:{paddingVertical:10,paddingHorizontal:14,borderRadius:10,backgroundColor:"#2563EB"},at:{color:"#fff",fontWeight:"800"},purchaseRow:{flexDirection:"row",paddingVertical:8,borderBottomWidth:1,borderBottomColor:"#DBEAFE"},totalCard:{backgroundColor:"#0F172A",borderRadius:16,padding:18},totalLabel:{color:"#CBD5E1",fontWeight:"700"},total:{fontSize:34,fontWeight:"900",color:"#fff",marginTop:3},dayTotal:{color:"#BFDBFE",marginTop:4}});