const STORAGE='comicmarket-map-v7';
const OFFICIAL='https://www.comiket.co.jp/info-a/C108/C108CtlgMap.html';
const DAYS=['1日目','2日目','3日目'];
const TRAVELERS=['花岡','菊池','石井','Akio','コナカ','松倉','砂','澤井','風也'];
const COLORS={花岡:'#ef4444',菊池:'#f97316',石井:'#eab308',Akio:'#22c55e',コナカ:'#06b6d4',松倉:'#3b82f6',砂:'#8b5cf6',澤井:'#ec4899',風也:'#64748b'};
const MAPS=[['東123','./maps/east123.webp',1320/571],['東7','./maps/east7.jpg',874/877],['西12','./maps/west12.webp',1201/860],['南12','./maps/south12.jpg',1253/698]];
const STATUS=[['ALL','すべて'],['UNVISITED','未訪問'],['PLANNED','購入予定'],['COMPLETED','購入済み'],['SOLD_OUT','完売']];
let state={day:'1日目',map:'東123',filter:'ALL',circles:[]},pending=null,editing=null,detail=null;
let scale=1,tx=0,ty=0,pointers=new Map(),gesture=null,moved=false;
const $=id=>document.getElementById(id),yen=n=>'¥'+Math.round(Number(n)||0).toLocaleString('ja-JP');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const total=c=>(c.items||[]).reduce((n,i)=>n+(+i.qty||0)*(+i.price||0),0);
function normalize(){state.day=DAYS.includes(state.day)?state.day:'1日目';state.map=MAPS.some(m=>m[0]===state.map)?state.map:'東123';state.circles=(Array.isArray(state.circles)?state.circles:[]).map(c=>({...c,day:DAYS.includes(c.day)?c.day:'1日目',map:MAPS.some(m=>m[0]===c.map)?c.map:'東123',traveler:TRAVELERS.includes(c.traveler)?c.traveler:'',items:Array.isArray(c.items)?c.items:[{name:c.item||'',qty:+c.qty||1,price:+c.price||0}],status:c.status||'UNVISITED'}))}
function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE));if(s)state=s}catch{}normalize();render()}
function save(){normalize();localStorage.setItem(STORAGE,JSON.stringify(state));render()}
function mapInfo(){return MAPS.find(m=>m[0]===state.map)||MAPS[0]}
function rows(){const q=($('search')?.value||'').toLowerCase().trim();return state.circles.filter(c=>c.day===state.day&&c.map===state.map&&(state.filter==='ALL'||c.status===state.filter)&&(!q||[c.name,c.space,c.buyer,c.traveler,...(c.items||[]).map(i=>i.name)].join(' ').toLowerCase().includes(q)))}
function render(){
 $('days').innerHTML=DAYS.map(d=>`<button type="button" data-day="${d}" class="${state.day===d?'active':''}">${d}</button>`).join('');
 $('maps').innerHTML=MAPS.map(m=>`<button type="button" data-map="${m[0]}" class="${state.map===m[0]?'active':''}">${m[0]}</button>`).join('');
 $('filters').innerHTML=STATUS.map(s=>`<button type="button" data-filter="${s[0]}" class="${state.filter===s[0]?'active':''}">${s[1]}</button>`).join('');
 const m=mapInfo();$('mapTitle').textContent=`${state.day}・${m[0]}`;$('mapImage').src=m[1];$('mapImage').alt=`コミケット公式 ${m[0]} 白地図`;$('mapCanvas').style.aspectRatio=m[2];
 renderMarkers();renderTotals();renderList();renderDetail();applyTransform();
}
function renderMarkers(){$('markers').innerHTML=state.circles.filter(c=>c.day===state.day&&c.map===state.map).map(c=>{const color=COLORS[c.traveler]||'#ef4444';return `<button type="button" class="marker" data-marker="${c.id}" title="${esc(c.name)}・${esc(c.traveler||'未指定')}" style="left:${c.x*100}%;top:${c.y*100}%;background:${color}"></button>`}).join('')}
function renderTotals(){const all=state.circles.filter(c=>c.day===state.day),rs=rows();$('circleCount').textContent=rs.length+'件';$('circleCount2').textContent=all.length;$('itemCount').textContent=all.reduce((n,c)=>n+(c.items||[]).reduce((x,i)=>x+(+i.qty||0),0),0);$('grandTotal').textContent=yen(all.reduce((n,c)=>n+total(c),0));$('dayTotals').innerHTML=DAYS.map(d=>`<div class="day-total"><span>${d}</span><strong>${yen(state.circles.filter(c=>c.day===d).reduce((n,c)=>n+total(c),0))}</strong></div>`).join('');const tv={};all.forEach(c=>{const k=c.traveler||'未指定';tv[k]=(tv[k]||0)+total(c)});$('travelerTotals').innerHTML=Object.entries(tv).map(([k,v])=>`<div class="buyer-total"><span>📍 ${esc(k)}</span><strong>${yen(v)}</strong></div>`).join('')||'<span class="muted">行く人が未登録</span>';const by={};all.forEach(c=>{const k=c.buyer||'未指定';by[k]=(by[k]||0)+total(c)});$('buyerTotals').innerHTML=Object.entries(by).map(([k,v])=>`<div class="buyer-total"><span>👤 ${esc(k)}</span><strong>${yen(v)}</strong></div>`).join('')||'<span class="muted">購入者が未登録</span>'}
function renderList(){const rs=rows();$('empty').classList.toggle('hidden',rs.length>0);$('list').innerHTML=rs.map(c=>`<article class="purchase" data-open="${c.id}"><div><h3>${esc(c.name)} <span class="status ${c.status}">${({UNVISITED:'未訪問',PLANNED:'購入予定',COMPLETED:'購入済み',SOLD_OUT:'完売'})[c.status]}</span></h3><p>${esc(c.space)} ・ 📍 ${esc(c.traveler||'未指定')} ・ 👤 ${esc(c.buyer||'未入力')}</p><div>${(c.items||[]).map(i=>`<span class="item-chip">${esc(i.name)} ×${i.qty} ${yen(i.qty*i.price)}</span>`).join('')}</div><div class="action-row">${STATUS.slice(1).map(s=>`<button type="button" class="ghost statusBtn" data-id="${c.id}" data-status="${s[0]}">${s[1]}</button>`).join('')}</div></div><div class="money">${yen(total(c))}</div></article>`).join('')}
function renderDetail(){const c=state.circles.find(x=>x.id===detail);if(!c){$('detail').classList.add('hidden');return}const color=COLORS[c.traveler]||'#ef4444';$('detail').classList.remove('hidden');$('detail').innerHTML=`<div class="section-head"><div><h2>${esc(c.name)}</h2><p class="muted">${c.day}・${c.map}・${esc(c.space)}</p></div><button type="button" class="ghost" id="closeDetail">閉じる</button></div><p>📍 行く人：<strong style="color:${color}">${esc(c.traveler||'未指定')}</strong></p><p>👤 購入者：<strong>${esc(c.buyer||'未入力')}</strong></p><div>${(c.items||[]).map(i=>`<div class="item-chip">${esc(i.name)} ×${i.qty} ${yen(i.qty*i.price)}</div>`).join('')}</div><h3 style="text-align:right">合計 ${yen(total(c))}</h3><div class="action-row"><button type="button" class="button primary" id="focusMap">📍 マップで表示</button><button type="button" class="ghost" id="editCircle">編集</button><button type="button" class="ghost" id="deleteCircle">削除</button></div>`;$('closeDetail').onclick=()=>{detail=null;renderDetail()};$('focusMap').onclick=()=>{state.day=c.day;state.map=c.map;detail=null;resetZoom();render();setTimeout(()=>$('mapSection').scrollIntoView({behavior:'smooth',block:'start'}),80)};$('editCircle').onclick=()=>openForm(c.x,c.y,c.id);$('deleteCircle').onclick=()=>{if(confirm('削除しますか？')){state.circles=state.circles.filter(x=>x.id!==c.id);detail=null;save()}}}
function addItem(item={name:'',qty:1,price:0}){const r=document.createElement('div');r.className='item-row';r.innerHTML=`<label>商品<input class="i-name" value="${esc(item.name)}" placeholder="新刊など"></label><label>数量<input class="i-qty" type="number" min="1" value="${item.qty||1}"></label><label>単価<input class="i-price" type="number" min="0" value="${item.price||0}"></label><button type="button" class="ghost removeItem">×</button>`;r.querySelectorAll('input').forEach(i=>i.oninput=formTotal);r.querySelector('.removeItem').onclick=()=>{r.remove();formTotal()};$('itemRows').appendChild(r)}
function formItems(){return [...document.querySelectorAll('#itemRows .item-row')].map(r=>({name:r.querySelector('.i-name').value.trim(),qty:+r.querySelector('.i-qty').value||1,price:+r.querySelector('.i-price').value||0})).filter(i=>i.name)}function formTotal(){$('formTotal').textContent=yen(formItems().reduce((n,i)=>n+i.qty*i.price,0))}
function openForm(x,y,id=null){pending={x,y};editing=id;const c=id?state.circles.find(v=>v.id===id):null;$('positionText').textContent=`地図位置：${(x*100).toFixed(1)}% / ${(y*100).toFixed(1)}%`;$('circleName').value=c?.name||'';$('space').value=c?.space||'';$('traveler').value=c?.traveler||'';$('buyer').value=c?.buyer||'';$('itemRows').innerHTML='';(c?.items?.length?c.items:[{}]).forEach(addItem);$('saveCircle').textContent=id?'変更を保存':'登録する';$('formCard').classList.remove('hidden');formTotal()}
function closeForm(){pending=null;editing=null;$('formCard').classList.add('hidden')}
function bounds(){const vp=$('mapViewport'),cv=$('mapCanvas');return{x:Math.max(0,(cv.offsetWidth*scale-vp.clientWidth)/2),y:Math.max(0,(cv.offsetHeight*scale-vp.clientHeight)/2)}}
function clamp(){const b=bounds();tx=Math.max(-b.x,Math.min(b.x,tx));ty=Math.max(-b.y,Math.min(b.y,ty))}
function applyTransform(){clamp();$('mapCanvas').style.transform=`translate3d(${tx}px,${ty}px,0) scale(${scale})`;$('zoomReset').textContent=Math.round(scale*100)+'%'}function resetZoom(){scale=1;tx=0;ty=0;applyTransform()}function zoom(n){scale=Math.max(.8,Math.min(5,n));applyTransform()}
function mapPoint(x,y){const r=$('mapCanvas').getBoundingClientRect();return{x:Math.max(0,Math.min(1,(x-r.left)/r.width)),y:Math.max(0,Math.min(1,(y-r.top)/r.height))}}
$('days').onclick=e=>{const b=e.target.closest('[data-day]');if(b){state.day=b.dataset.day;resetZoom();render()}};$('maps').onclick=e=>{const b=e.target.closest('[data-map]');if(b){state.map=b.dataset.map;resetZoom();render()}};$('filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){state.filter=b.dataset.filter;render()}};
$('registerMode').onclick=()=>{const on=$('mapModeHint').classList.contains('hidden');$('mapModeHint').classList.toggle('hidden',!on);$('registerMode').textContent=on?'登録モード終了':'＋ 地図から登録';$('mapViewport').classList.toggle('registering',on)};
const vp=$('mapViewport');vp.addEventListener('pointerdown',e=>{if(e.target.closest('.marker'))return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});moved=false;if(pointers.size===1)gesture={x:e.clientX,y:e.clientY,tx,ty,dist:null};else if(pointers.size===2){const a=[...pointers.values()];gesture={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),scale}}},{passive:false});vp.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&gesture?.dist===null){const p=pointers.get(e.pointerId);tx=gesture.tx+p.x-gesture.x;ty=gesture.ty+p.y-gesture.y;if(Math.hypot(p.x-gesture.x,p.y-gesture.y)>6)moved=true;applyTransform()}else if(pointers.size===2&&gesture?.dist){const a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);scale=Math.max(.8,Math.min(5,gesture.scale*d/gesture.dist));moved=true;applyTransform()}},{passive:false});vp.addEventListener('pointerup',e=>{const g=gesture;pointers.delete(e.pointerId);if(g&&!moved&&!pointers.size&&g.dist===null&&vp.classList.contains('registering')){const p=mapPoint(e.clientX,e.clientY);openForm(p.x,p.y);vp.classList.remove('registering');$('mapModeHint').classList.add('hidden');$('registerMode').textContent='＋ 地図から登録'}if(!pointers.size)gesture=null},{passive:false});vp.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);if(!pointers.size)gesture=null});vp.addEventListener('wheel',e=>{e.preventDefault();zoom(scale+(e.deltaY<0?.15:-.15))},{passive:false});
$('markers').onclick=e=>{const b=e.target.closest('[data-marker]');if(b){detail=b.dataset.marker;renderDetail()}};$('zoomIn').onclick=()=>zoom(scale+.25);$('zoomOut').onclick=()=>zoom(scale-.25);$('zoomReset').onclick=resetZoom;$('cancelForm').onclick=closeForm;$('addItem').onclick=()=>addItem();
$('saveCircle').onclick=()=>{if(!pending)return alert('地図上の位置を指定してください');const name=$('circleName').value.trim(),space=$('space').value.trim(),items=formItems();if(!name||!space)return alert('サークル名とスペースは必須です');if(!items.length)return alert('購入するものを1件以上入力してください');const data={day:state.day,map:state.map,name,space,traveler:$('traveler').value,buyer:$('buyer').value.trim(),items,x:pending.x,y:pending.y};if(editing){const c=state.circles.find(c=>c.id===editing);if(c)Object.assign(c,data)}else state.circles.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),...data,status:'UNVISITED'});save();closeForm()};
$('search').oninput=render;$('list').onclick=e=>{const s=e.target.closest('.statusBtn');if(s){e.stopPropagation();const c=state.circles.find(c=>c.id===s.dataset.id);if(c){c.status=s.dataset.status;save()}return}const a=e.target.closest('[data-open]');if(a){detail=a.dataset.open;renderDetail()}};$('officialLink').onclick=()=>window.open(OFFICIAL,'_blank','noopener');
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-nav]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=b.dataset.nav==='map'?'mapSection':b.dataset.nav==='list'?'listSection':'moneySection';$(t)?.scrollIntoView({behavior:'smooth',block:'start'})});window.onresize=applyTransform;
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));load();