const STORAGE='comicmarket-map-v6';
const OFFICIAL='https://www.comiket.co.jp/info-a/C108/C108CtlgMap.html';
const MAPS=[{id:'東123',label:'東123',src:'./maps/east123.webp',ratio:1320/571,available:true},{id:'西12',label:'西12',src:'./maps/west12.webp',ratio:1201/860,available:true},{id:'東7',label:'東7',src:'',ratio:1,available:false},{id:'南12',label:'南12',src:'',ratio:1,available:false}];
const STATUS=[['ALL','すべて'],['UNVISITED','未訪問'],['PLANNED','購入予定'],['COMPLETED','購入済み'],['SOLD_OUT','完売']];
let state={day:'1日目',map:'東123',filter:'ALL',circles:[]};let pendingPos=null,editingId=null,detailId=null,channel=null;
let scale=1,tx=0,ty=0,pointers=new Map(),gestureStart=null,moved=false;try{channel=new BroadcastChannel('comicmarket-map-live')}catch{}
const $=id=>document.getElementById(id),yen=n=>'¥'+Math.round(Number(n)||0).toLocaleString('ja-JP'),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const circleTotal=c=>(c.items||[]).reduce((n,i)=>n+(Number(i.qty)||0)*(Number(i.price)||0),0),itemTotal=c=>(c.items||[]).reduce((n,i)=>n+(Number(i.qty)||0),0),statusLabel=s=>({UNVISITED:'未訪問',PLANNED:'購入予定',COMPLETED:'購入済み',SOLD_OUT:'完売'}[s]||'未訪問');
function normalize(){state.circles=(state.circles||[]).map(c=>({...c,items:Array.isArray(c.items)?c.items:[{name:c.item||'',qty:Number(c.qty)||1,price:Number(c.price)||0}],status:c.status||'UNVISITED'}))}
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE)||'null');if(x&&Array.isArray(x.circles))state=x}catch{}normalize();render()}
function save(broadcast=true){normalize();localStorage.setItem(STORAGE,JSON.stringify(state));if(broadcast&&channel)channel.postMessage(state);render()}
if(channel)channel.onmessage=e=>{if(e.data&&Array.isArray(e.data.circles)){state=e.data;normalize();render()}};window.addEventListener('storage',e=>{if(e.key===STORAGE)load()});
function currentMap(){return MAPS.find(m=>m.id===state.map)||MAPS[0]}
function filtered(){const q=($('search')?.value||'').trim().toLowerCase();return state.circles.filter(c=>c.day===state.day&&c.map===state.map&&(state.filter==='ALL'||c.status===state.filter)&&(!q||[c.name,c.space,c.buyer,...(c.items||[]).map(i=>i.name)].join(' ').toLowerCase().includes(q)))}
function render(){$('days').innerHTML=['1日目','2日目','3日目'].map(d=>`<button class="${state.day===d?'active':''}" data-day="${d}">${d}</button>`).join('');$('maps').innerHTML=MAPS.map(m=>`<button class="${state.map===m.id?'active':''}" data-map="${m.id}" ${m.available?'':'disabled'}>${m.label}${m.available?'':' 準備中'}</button>`).join('');$('filters').innerHTML=STATUS.map(([k,l])=>`<button class="${state.filter===k?'active':''}" data-filter="${k}">${l}</button>`).join('');const m=currentMap();$('mapTitle').textContent=`${state.day}・${m.label}`;$('mapHint').textContent=m.available?'画像を直接操作できます。ピンチで拡大、ドラッグで移動':'この地区の地図画像は未提供です';$('mapImage').src=m.src;$('mapImage').alt=`コミケット公式 ${m.label} 白地図`;$('mapCanvas').style.aspectRatio=m.ratio;renderMarkers();renderTotals();renderList();renderDetail();updateZoomLabel()}
function renderMarkers(){$('markers').innerHTML=state.circles.filter(c=>c.day===state.day&&c.map===state.map).map(c=>`<button class="marker ${c.status==='COMPLETED'?'completed':c.status==='SOLD_OUT'?'sold':c.status==='PLANNED'?'planned':''}" data-marker="${c.id}" title="${esc(c.name)}" style="left:${c.x*100}%;top:${c.y*100}%" aria-label="${esc(c.name)}"></button>`).join('')}
function renderTotals(){const rows=filtered(),all=state.circles.filter(c=>c.day===state.day),total=all.reduce((n,c)=>n+circleTotal(c),0),items=all.reduce((n,c)=>n+itemTotal(c),0);$('circleCount').textContent=rows.length+'件';$('circleCount2').textContent=all.length;$('itemCount').textContent=items;$('grandTotal').textContent=yen(total);$('dayTotals').innerHTML=['1日目','2日目','3日目'].map(d=>{const t=state.circles.filter(c=>c.day===d).reduce((n,c)=>n+circleTotal(c),0);return `<div class="day-total"><span>${d}</span><strong>${yen(t)}</strong></div>`}).join('');const buyers={};all.forEach(c=>{const b=c.buyer?.trim()||'未指定';buyers[b]=(buyers[b]||0)+circleTotal(c)});$('buyerTotals').innerHTML=Object.entries(buyers).sort((a,b)=>b[1]-a[1]).map(([b,t])=>`<div class="buyer-total"><span>👤 ${esc(b)}</span><strong>${yen(t)}</strong></div>`).join('')||'<span class="muted">購入者がまだ登録されていません</span>'}
function renderList(){const rows=filtered();$('empty').classList.toggle('hidden',rows.length>0);$('list').innerHTML=rows.map(c=>`<article class="purchase" data-open="${c.id}"><div><h3>${esc(c.name)} <span class="status ${c.status}">${statusLabel(c.status)}</span></h3><p>${esc(c.space)} ・ 👤 ${esc(c.buyer||'未入力')}</p><div>${(c.items||[]).map(i=>`<span class="item-chip">${esc(i.name||'商品')} ×${Number(i.qty)||0} ${yen((Number(i.qty)||0)*(Number(i.price)||0))}</span>`).join('')}</div><div class="action-row">${STATUS.slice(1).map(([s,l])=>`<button class="ghost statusBtn" data-id="${c.id}" data-status="${s}">${l}</button>`).join('')}</div></div><div class="money">${yen(circleTotal(c))}<br><small>${esc(c.map)} ${esc(c.space)}</small></div></article>`).join('')}
function renderDetail(){const c=state.circles.find(x=>x.id===detailId);if(!c){$('detail').classList.add('hidden');return}$('detail').classList.remove('hidden');$('detail').innerHTML=`<div class="section-head"><div><h2>${esc(c.name)}</h2><p class="muted">${esc(c.day)}・${esc(c.map)}・${esc(c.space)}</p></div><button class="ghost" id="closeDetail">閉じる</button></div><p>👤 購入者：<strong>${esc(c.buyer||'未入力')}</strong></p><div>${(c.items||[]).map(i=>`<div class="item-chip">${esc(i.name)} ×${Number(i.qty)||0}　${yen((Number(i.qty)||0)*(Number(i.price)||0))}</div>`).join('')}</div><h3 style="text-align:right">合計 ${yen(circleTotal(c))}</h3><div class="action-row"><button class="button primary" id="focusMap">📍 マップで表示</button><button class="ghost" id="editCircle">編集</button><button class="ghost" id="deleteCircle">削除</button></div>`;$('closeDetail').onclick=()=>{detailId=null;renderDetail()};$('focusMap').onclick=()=>{state.day=c.day;state.map=c.map;detailId=null;render();resetZoom();setTimeout(()=>scrollToMapMarker(c.id),60)};$('editCircle').onclick=()=>openForm(c.x,c.y,c.id);$('deleteCircle').onclick=()=>{if(confirm('このサークルを削除しますか？')){state.circles=state.circles.filter(x=>x.id!==c.id);detailId=null;save()}}}
function scrollToMapMarker(id){document.querySelector(`[data-marker="${id}"]`)?.scrollIntoView({behavior:'smooth',block:'center',inline:'center'})}
function openForm(x,y,id=null){pendingPos={x,y};editingId=id;const c=id?state.circles.find(v=>v.id===id):null;$('positionText').textContent=`地図位置：${(x*100).toFixed(1)}% / ${(y*100).toFixed(1)}%`;$('circleName').value=c?.name||'';$('space').value=c?.space||'';$('buyer').value=c?.buyer||'';$('itemRows').innerHTML='';(c?.items?.length?c.items:[{name:'',qty:1,price:0}]).forEach(addItemRow);$('saveCircle').textContent=id?'変更を保存':'登録する';$('formCard').classList.remove('hidden');updateFormTotal();$('circleName').focus()}
function closeForm(){pendingPos=null;editingId=null;$('formCard').classList.add('hidden')}
function addItemRow(item={name:'',qty:1,price:0}){const row=document.createElement('div');row.className='item-row';row.innerHTML=`<label>商品<input class="i-name" value="${esc(item.name)}" placeholder="新刊など"></label><label>数量<input class="i-qty" type="number" min="1" value="${Number(item.qty)||1}"></label><label>単価<input class="i-price" type="number" min="0" value="${Number(item.price)||0}"></label><button class="ghost removeItem" type="button">×</button>`;row.querySelectorAll('input').forEach(i=>i.addEventListener('input',updateFormTotal));row.querySelector('.removeItem').onclick=()=>{row.remove();updateFormTotal()};$('itemRows').appendChild(row)}
function getFormItems(){return [...document.querySelectorAll('.item-row')].map(r=>({name:r.querySelector('.i-name').value.trim(),qty:Number(r.querySelector('.i-qty').value)||1,price:Number(r.querySelector('.i-price').value)||0})).filter(i=>i.name)}function updateFormTotal(){$('formTotal').textContent=yen(getFormItems().reduce((n,i)=>n+i.qty*i.price,0))}
function resetZoom(){scale=1;tx=0;ty=0;applyTransform()}function applyTransform(){$('mapCanvas').style.transform=`translate3d(${tx}px,${ty}px,0) scale(${scale})`;updateZoomLabel()}function updateZoomLabel(){$('zoomReset').textContent=Math.round(scale*100)+'%'}function zoomAt(next){scale=Math.max(.8,Math.min(5,next));applyTransform()}function pointerPos(e){return{x:e.clientX,y:e.clientY}}function mapPoint(x,y){const r=$('mapCanvas').getBoundingClientRect();return{x:Math.max(0,Math.min(1,(x-r.left)/r.width)),y:Math.max(0,Math.min(1,(y-r.top)/r.height))}}
$('days').onclick=e=>{const b=e.target.closest('[data-day]');if(b){state.day=b.dataset.day;resetZoom();render()}};$('maps').onclick=e=>{const b=e.target.closest('[data-map]');if(b&&!b.disabled){state.map=b.dataset.map;resetZoom();render()}};$('filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){state.filter=b.dataset.filter;render()}};
$('registerMode').onclick=()=>{const active=!$('mapModeHint').classList.contains('hidden');$('mapModeHint').classList.toggle('hidden',active);$('registerMode').textContent=active?'＋ 地図から登録':'登録モード終了';$('mapViewport').classList.toggle('registering',!active)};
$('mapViewport').addEventListener('pointerdown',e=>{if(e.target.closest('.marker'))return;e.currentTarget.setPointerCapture(e.pointerId);pointers.set(e.pointerId,pointerPos(e));moved=false;if(pointers.size===1)gestureStart={x:e.clientX,y:e.clientY,tx,ty};if(pointers.size===2){const a=[...pointers.values()];gestureStart={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),scale}});
$('mapViewport').addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,pointerPos(e));if(pointers.size===1&&gestureStart?.dist==null){const p=pointers.get(e.pointerId);tx=gestureStart.tx+p.x-gestureStart.x;ty=gestureStart.ty+p.y-gestureStart.y;if(Math.abs(p.x-gestureStart.x)+Math.abs(p.y-gestureStart.y)>6)moved=true;applyTransform()}else if(pointers.size===2){const a=[...pointers.values()];const d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(gestureStart?.dist){scale=Math.max(.8,Math.min(5,gestureStart.scale*d/gestureStart.dist));applyTransform()}}});
$('mapViewport').addEventListener('pointerup',e=>{const start=gestureStart;pointers.delete(e.pointerId);if(start&&!moved&&pointers.size===0&&start.dist==null&&!$('mapModeHint').classList.contains('hidden')){const p=mapPoint(e.clientX,e.clientY);openForm(p.x,p.y);$('mapModeHint').classList.add('hidden');$('registerMode').textContent='＋ 地図から登録'}if(pointers.size===0)gestureStart=null});$('mapViewport').addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);if(pointers.size===0)gestureStart=null});
$('markers').onclick=e=>{const b=e.target.closest('[data-marker]');if(b){detailId=b.dataset.marker;renderDetail()}};$('zoomIn').onclick=()=>zoomAt(scale+.25);$('zoomOut').onclick=()=>zoomAt(scale-.25);$('zoomReset').onclick=resetZoom;$('mapViewport').addEventListener('wheel',e=>{e.preventDefault();zoomAt(scale+(e.deltaY<0?.15:-.15))},{passive:false});
$('cancelForm').onclick=closeForm;$('addItem').onclick=()=>addItemRow();$('saveCircle').onclick=()=>{if(!pendingPos)return alert('地図上の位置を指定してください');const name=$('circleName').value.trim(),space=$('space').value.trim(),items=getFormItems();if(!name||!space)return alert('サークル名とスペースは必須です');if(!items.length)return alert('購入するものを1件以上入力してください');const base={day:state.day,map:state.map,name,space,buyer:$('buyer').value.trim(),items,x:pendingPos.x,y:pendingPos.y};if(editingId){const c=state.circles.find(x=>x.id===editingId);Object.assign(c,base)}else state.circles.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),...base,status:'UNVISITED'});save();closeForm()};
$('search').oninput=render;$('list').onclick=e=>{const s=e.target.closest('.statusBtn');if(s){const c=state.circles.find(x=>x.id===s.dataset.id);if(c){c.status=s.dataset.status;save()}return}const a=e.target.closest('[data-open]');if(a){detailId=a.dataset.open;renderDetail()}};$('officialLink').onclick=()=>window.open(OFFICIAL,'_blank','noopener');
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-nav]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const n=b.dataset.nav;if(n==='map')window.scrollTo({top:0,behavior:'smooth'});if(n==='list')$('list').scrollIntoView({behavior:'smooth'});if(n==='money')document.querySelector('.totals').scrollIntoView({behavior:'smooth'})});
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();deferredPrompt=null};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));load();