(() => {
  const KEY='comicmarket-map-v7';
  const labels={UNVISITED:'未訪問',PLANNED:'購入予定',COMPLETED:'購入済み',SOLD_OUT:'完売'};
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const yen=n=>'¥'+Math.round(Number(n)||0).toLocaleString('ja-JP');
  const total=c=>(c.items||[]).reduce((n,i)=>n+(+i.qty||0)*(+i.price||0),0);
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const rank=ch=>/^[ぁ-ゖ]$/.test(ch)?0:/^[ァ-ヺ]$/.test(ch)?1:/^[A-Z]$/.test(ch)?2:/^[a-z]$/.test(ch)?3:/^[0-9]$/.test(ch)?4:5;
  function compareSpace(a,b){const clean=s=>String(s||'').trim().replace(/\s+/g,'');const aa=clean(a),bb=clean(b);const dr=s=>s.startsWith('東')?0:s.startsWith('西')?1:s.startsWith('南')?2:3;if(dr(aa)!==dr(bb))return dr(aa)-dr(bb);const x=aa.slice(1),y=bb.slice(1);let i=0;while(i<x.length&&i<y.length){const cx=x[i],cy=y[i];if(/\d/.test(cx)&&/\d/.test(cy)){const mx=x.slice(i).match(/^\d+/)[0],my=y.slice(i).match(/^\d+/)[0];if(+mx!==+my)return +mx-+my;i+=Math.max(mx.length,my.length);continue;}const rx=rank(cx),ry=rank(cy);if(rx!==ry)return rx-ry;if(cx!==cy)return cx.localeCompare(cy,'ja');i++;}return x.length-y.length;}
  const fmtTime=iso=>{if(!iso)return '';const d=new Date(iso);if(Number.isNaN(d.getTime()))return '';return `${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}:${String(d.getSeconds()).padStart(2,'0')}`};
  function sortCurrent(){const s=read(),day=s.day||'1日目',map=s.map||'東123',filter=s.filter||'ALL',q=(document.getElementById('search')?.value||'').toLowerCase().trim();return(s.circles||[]).filter(c=>c.day===day&&c.map===map&&(filter==='ALL'||c.status===filter)&&(!q||[c.name,c.space,c.buyer,c.traveler,...(c.items||[]).map(i=>i.name)].join(' ').toLowerCase().includes(q))).sort((a,b)=>compareSpace(a.space,b.space)||String(a.name||'').localeCompare(String(b.name||''),'ja'));}
  function addSortButton(){const list=document.getElementById('list');if(!list||document.getElementById('sortList'))return;const head=list.closest('.card')?.querySelector('.section-head');if(!head)return;const b=document.createElement('button');b.id='sortList';b.type='button';b.className='ghost';b.textContent='並び替え：東→西→南';head.appendChild(b);b.onclick=()=>{renderSortedList();b.textContent='並び順：東→西→南';};}
  function renderSortedList(){const rs=sortCurrent(),list=document.getElementById('list'),empty=document.getElementById('empty');if(!list)return;if(empty)empty.classList.toggle('hidden',rs.length>0);list.innerHTML=rs.map(c=>`<article class="purchase" data-open="${esc(c.id)}"><div><h3>${esc(c.name)} <span class="status ${esc(c.status)}">${labels[c.status]||c.status}</span></h3><p>${esc(c.space)} ・ 📍 ${esc(c.traveler||'未指定')} ・ 👤 ${esc(c.buyer||'未入力')}</p><div>${(c.items||[]).map(i=>`<span class="item-chip">${esc(i.name)} ×${i.qty} ${yen(i.qty*i.price)}</span>`).join('')}</div>${c.status==='COMPLETED'&&c.completedAt?`<p class="status-time">購入済み：${fmtTime(c.completedAt)}</p>`:''}${c.status==='SOLD_OUT'&&c.soldOutAt?`<p class="status-time">完売：${fmtTime(c.soldOutAt)}</p>`:''}<div class="action-row">${[['UNVISITED','未訪問'],['PLANNED','購入予定'],['COMPLETED','購入済み'],['SOLD_OUT','完売']].map(x=>`<button type="button" class="ghost statusBtn" data-id="${esc(c.id)}" data-status="${x[0]}">${x[1]}</button>`).join('')}</div></div><div class="money">${yen(total(c))}</div></article>`).join('');}
  function decorateMarkers(){const s=read(),by=new Map((s.circles||[]).map(c=>[c.id,c]));document.querySelectorAll('[data-marker]').forEach(m=>{const c=by.get(m.dataset.marker);if(!c)return;m.style.borderWidth='3px';m.style.borderStyle='solid';m.style.borderColor=c.status==='COMPLETED'?'#16a34a':c.status==='SOLD_OUT'?'#dc2626':'#fff';m.title=`${c.name}・${labels[c.status]||c.status}`;});}
  function setStatusTime(id,status){if(status!=='COMPLETED'&&status!=='SOLD_OUT')return;const s=read();const c=(s.circles||[]).find(x=>x.id===id);if(!c)return;const now=new Date().toISOString();if(status==='COMPLETED'){c.completedAt=now;delete c.soldOutAt;}else{c.soldOutAt=now;delete c.completedAt;}localStorage.setItem(KEY,JSON.stringify(s));renderTimeList();decorateMarkers();}
  function renderTimeList(){const s=read(),list=document.getElementById('timeList'),empty=document.getElementById('timeEmpty');if(!list)return;const rows=(s.circles||[]).filter(c=>c.status==='COMPLETED'&&c.completedAt||c.status==='SOLD_OUT'&&c.soldOutAt).map(c=>({c,t:c.status==='COMPLETED'?c.completedAt:c.soldOutAt,label:c.status==='COMPLETED'?'購入済み':'完売'})).sort((a,b)=>new Date(b.t)-new Date(a.t));if(empty)empty.classList.toggle('hidden',rows.length>0);list.innerHTML=rows.map(r=>`<article class="purchase"><div><h3>${esc(r.c.name)} <span class="status ${esc(r.c.status)}">${r.label}</span></h3><p>${esc(r.c.day||'')} ・ ${esc(r.c.map||'')} ・ ${esc(r.c.space||'')} ・ 📍 ${esc(r.c.traveler||'未指定')}</p><p class="status-time">⏱ ${fmtTime(r.t)}</p></div><div class="money">${yen(total(r.c))}</div></article>`).join('');}
  function showNav(name){const ids={map:'mapSection',list:'listSection',money:'moneySection',time:'timeSection'};const target=document.getElementById(ids[name]);if(!target)return;document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));document.querySelectorAll('main>section').forEach(s=>{if(s.id&&ids[name]&&['mapSection','listSection','moneySection','timeSection'].includes(s.id))s.classList.toggle('hidden',s.id!==ids[name]);});target.classList.remove('hidden');target.scrollIntoView({behavior:'smooth',block:'start'});if(name==='time')renderTimeList();}
  document.addEventListener('click',e=>{const nav=e.target.closest('.bottom-nav button');if(nav){e.preventDefault();showNav(nav.dataset.nav);return;}const btn=e.target.closest('.statusBtn');if(btn){setTimeout(()=>{setStatusTime(btn.dataset.id,btn.dataset.status);renderSortedList();},0);}},true);
  window.addEventListener('storage',e=>{if(e.key===KEY)setTimeout(()=>{decorateMarkers();renderTimeList();},0)});
  const observer=new MutationObserver(()=>{addSortButton();decorateMarkers();});observer.observe(document.body,{childList:true,subtree:true});
  window.addEventListener('load',()=>{addSortButton();decorateMarkers();renderTimeList();document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>showNav(b.dataset.nav)));});
  setTimeout(()=>{addSortButton();decorateMarkers();renderTimeList();},100);
})();
