(() => {
  const PDFS={'東123':'https://www.comiket.co.jp/info-a/C108/C108Map_e123_B4.pdf','東456':'https://www.comiket.co.jp/info-a/C107/C107Map_e456_B4.pdf','西12':'https://www.comiket.co.jp/info-a/C108/C108Map_w12_B4.pdf'};
  let last='',loading=null,ready=false;
  function loadPdfJs(){if(ready&&window.pdfjsLib)return Promise.resolve();if(loading)return loading;loading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.async=true;s.onload=()=>{if(window.pdfjsLib){pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';ready=true;resolve()}else reject(new Error('PDF.js unavailable'))};s.onerror=reject;document.head.appendChild(s)}).catch(e=>{loading=null;throw e});return loading}
  async function render(){const title=document.getElementById('mapTitle'),canvas=document.getElementById('pdfMapCanvas'),img=document.getElementById('mapImage');if(!title||!canvas||!window.pdfjsLib)return;const map=(title.textContent.match(/・([^・]+)$/)||[])[1],url=PDFS[map];if(!url||url===last)return;if(window.CMEvent?.get?.()!=='C108'&&map!=='東456')return;last=url;try{const pdf=await pdfjsLib.getDocument({url}).promise,page=await pdf.getPage(1),base=page.getViewport({scale:1}),dpr=Math.min(2,window.devicePixelRatio||1),box=document.getElementById('mapViewport'),width=Math.max(320,box.clientWidth),renderScale=width/base.width*dpr,view=page.getViewport({scale:renderScale});canvas.width=view.width;canvas.height=view.height;canvas.style.width=(view.width/dpr)+'px';canvas.style.height=(view.height/dpr)+'px';await page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport:view}).promise;img.style.display='none';canvas.style.display='block';document.getElementById('mapCanvas').style.aspectRatio=base.width/base.height}catch(e){console.warn('PDF high-resolution render failed; local image remains active.',e);img.style.display='block';canvas.style.display='none';last=''}}
  function enhance(){loadPdfJs().then(render).catch(()=>{})}
  window.addEventListener('pointerdown',enhance,{once:true,passive:true});window.addEventListener('wheel',enhance,{once:true,passive:true});document.addEventListener('click',e=>{if(e.target.closest('#zoomIn,#zoomOut,#zoomReset,[data-map]'))enhance()},{passive:true});
  const idle=window.requestIdleCallback||((cb)=>setTimeout(cb,2500));idle(()=>enhance());
  window.CMHighResMap={refresh:()=>{last='';enhance()}};
})();
