(() => {
  const nav={map:'mapSection',list:'listSection',money:'moneySection',time:'timeSection'};
  const keyText=a=>{const p=a.querySelector('p')?.textContent||'';return p.split('・')[0].trim().replace(/\s+/g,' ')};
  const rank=c=>/[ぁ-ゖ]/.test(c)?0:/[ァ-ヺ]/.test(c)?1:/[A-Z]/.test(c)?2:/[a-z]/.test(c)?3:4;
  function cmp(a,b){const aa=keyText(a),bb=keyText(b);const tok=s=>{const m=s.match(/\s+(.+)$/);return m?m[1]:s};const x=tok(aa),y=tok(bb);const first=(x.match(/[ぁ-ゖァ-ヺA-Za-z]/)||[])[0],second=(y.match(/[ぁ-ゖァ-ヺA-Za-z]/)||[])[0];if(first&&second){const r=rank(first)-rank(second);if(r)return r}const dir=s=>s.includes('東')?0:s.includes('西')?1:s.includes('南')?2:3;const d=dir(x)-dir(y);if(d)return d;const nx=(x.match(/\d+/)||['999999'])[0],ny=(y.match(/\d+/)||['999999'])[0];if(+nx!==+ny)return +nx-+ny;return x.localeCompare(y,'ja')}
  function sortList(){const l=document.getElementById('list');if(!l)return;[...l.children].sort(cmp).forEach(x=>l.appendChild(x))}
  function navTo(name){const id=nav[name];if(!id)return;document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));document.querySelectorAll('main>section').forEach(s=>{if(Object.values(nav).includes(s.id))s.classList.toggle('hidden',s.id!==id)});document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
  function travelerPins(){const select=document.getElementById('travelerSelect');if(!select)return;window.cmTravelerFilter=select.value;let data={};try{data=JSON.parse(localStorage.getItem('comicmarket-map-v7')||'{}')}catch{}const by=new Map((data.circles||[]).map(c=>[c.id,c]));document.querySelectorAll('#markers [data-marker]').forEach(m=>{const c=by.get(m.dataset.marker);m.style.display=(!window.cmTravelerFilter||window.cmTravelerFilter==='ALL'||c?.traveler===window.cmTravelerFilter)?'grid':'none'});}
  function timeOnly(){document.querySelectorAll('#timeList .time-row').forEach(r=>{const span=r.querySelector('span');if(!span)return;const text=span.textContent;const match=text.match(/(\d{4}\/\d{1,2}\/\d{1,2}.*)$/);if(match)span.textContent=match[1]})}
  function addItemFallback(){const rows=document.getElementById('itemRows');if(!rows)return;const r=document.createElement('div');r.className='item-row';r.innerHTML='<label>商品<input class="i-name" autocomplete="off"></label><label>数量<input class="i-qty" type="number" min="1" value="1"></label><label>単価<input class="i-price" type="number" min="0" value="0"></label><button type="button" class="ghost removeItem">×</button>';rows.appendChild(r);r.querySelectorAll('input').forEach(x=>x.addEventListener('input',()=>window.formTotal?.()));r.querySelector('.removeItem').addEventListener('click',()=>{r.remove();window.formTotal?.()});window.formTotal?.()}
  document.addEventListener('click',e=>{
    const b=e.target.closest('[data-nav]');if(b){e.preventDefault();e.stopImmediatePropagation();navTo(b.dataset.nav);return}
    if(e.target.closest('#sortList')){e.preventDefault();sortList();return}
    if(e.target.closest('#addItem')){e.preventDefault();e.stopImmediatePropagation();addItemFallback();return}
  },true);
  document.addEventListener('change',e=>{if(e.target.id==='travelerSelect'){e.stopImmediatePropagation();travelerPins()}},true);
  const obs=new MutationObserver(()=>{sortList();timeOnly();const s=document.getElementById('travelerSelect');if(s&&window.cmTravelerFilter&&s.value!==window.cmTravelerFilter)s.value=window.cmTravelerFilter;travelerPins()});obs.observe(document.body,{childList:true,subtree:true});
  const style=document.createElement('style');style.textContent=`.marker{width:18px!important;height:18px!important;min-width:18px!important;min-height:18px!important;border-width:2px!important;border-style:solid!important;border-radius:50%!important;display:grid!important;place-items:center!important;padding:0!important;font-size:10px!important;line-height:1!important;z-index:3}.priority-star{color:#fff;text-shadow:0 0 2px #000;font-size:11px}.event-tabs{display:flex;gap:4px;overflow-x:auto;padding:6px 0;margin-bottom:8px;position:sticky;top:0;z-index:8;background:inherit}.event-tabs button{flex:0 0 auto;border:1px solid #cbd5e1;background:#fff;border-radius:8px;padding:6px 9px}.event-tabs button.active{background:#2563eb;color:#fff;border-color:#2563eb}.toolbar-row{display:flex;gap:8px;align-items:center;margin:6px 0}.toolbar-row select{min-width:120px}.time-row{display:flex;justify-content:space-between;gap:12px;padding:12px;border-bottom:1px solid #e5e7eb}.time-row strong{font-weight:700}.status.SOLD_OUT{border-color:#dc2626!important}.status.COMPLETED{border-color:#16a34a!important}.map-canvas,.map-viewport{width:100%;max-width:100%;overflow:hidden}.map-canvas canvas{display:block;width:100%!important;height:100%!important;max-width:100%!important;user-select:none;-webkit-user-select:none}.map-canvas img{display:block;width:100%;max-width:100%;user-select:none;-webkit-user-drag:none}@media(max-width:700px){main{width:100%;max-width:100vw;overflow-x:hidden}.map-card{width:100%;max-width:100vw}.map-viewport{width:100%;max-width:100vw}.map-canvas{width:100%!important;max-width:100%!important}.map-toolbar{width:100%;overflow:hidden}.map-toolbar .seg{width:100%;max-width:100%;overflow-x:auto}.event-tabs{width:100%;max-width:100vw;overflow-x:auto;white-space:nowrap}}
`;
  document.head.appendChild(style);
})();
